### ISSUE TITLE
Documentation script linking is not corect

### ISSUE THREAD

**Issue by marinescud** [Serhioromano/angular-aws-s3-upload#10]
On the install section of the documentation is suggested to put a script with this url: src="bower_components/angular-aws-s3-uploader/angular-s3.js"
Insted it should be with a different folder name:
BAD - ../bower_components/angular-aws-s3-uploader/...
GUD - ../bower_components/angular-aws-s3-upload/...

**Comment by Serhioromano** [comment]
Can you edit it? I'll accept the change.
