### ISSUE TITLE
File select not opening

### ISSUE THREAD

**Issue by Hexalyse** [Serhioromano/angular-aws-s3-upload#5]
I tried installing your directive and did not manage to make it work (no file selector appears when I click on the directive button). So I went and tried your example index.html file.
I have no error in the console, everything is working fine, but when I click on "Select a file" (or on the select mutiple files button), nothing happens. No file selector appears.

Am I missing something ? Am I doing something wrong ?

**Comment by Serhioromano** [comment]
try to see it in inspector. The technique that is used there is that there is file input field inside the button transparent. You do not see it but you click it.
